[tool.poetry]
name = "terra-py"
version = "0.1.0"
description = "Python library for Terra Core"
authors = ["etienne-napoleone <etienne@terra.money>"]

[tool.poetry.dependencies]
python = "^3.6"
btclib = "^2019.6"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
flake8 = "^3.7"
coverage = "^4.5"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
