version: 2

jobs:

  lint-and-test:
    docker:
      - image: circleci/python:3.6.8
    steps:
      - checkout
      - restore_cache:
          keys: 
            - deps-{{ checksum "poetry.lock" }}
      - run:
          name: Install Dependencies
          command: |
            poetry install
      - save_cache:
          key: deps-{{ checksum "poetry.lock" }}
          paths: 
            - /home/circleci/.cache/pypoetry/virtualenvs
      - run:
          name: Lint
          command: |
            poetry run flake8 .
      - run:
          name: Static type checking
          command: |
            poetry run mypy --ignore-missing-imports .
      - run:
          name: Test and coverage
          command: |
            poetry run coverage run --source terra -m pytest -v
            poetry run codecov --token=${CODECOV_TOKEN}

  publish:
    docker:
        - image: circleci/python:3.6.8
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            poetry install
      - run:
          name: Build
          command: |
            poetry build
      - run:
          name: Publish to Github
          command: |
            poetry run githubrelease release ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME} create ${CIRCLE_TAG} --publish "dist/*"
      - run:
          name: Publish to PyPI
          command: |
            poetry publish --username "${PYPI_USERNAME}" --password "${PYPI_PASSWORD}" --no-interaction


  docs:
    docker:
        - image: circleci/python:3.6.8
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            poetry install
      - add_ssh_keys:
          fingerprints:
            - "19:9e:15:1c:10:8b:6a:77:be:ca:ed:92:66:d5:c4:fa"
      - run:
          name: Publish to GH Pages
          command: |
            git config user.email "deploy@terra.money"
            git config user.name "docs deployer"
            poetry run mkdocs gh-deploy -c -m "Deploying docs {sha} [ci skip]"

workflows:
  version: 2

  lint-test-publish-workflow:
    jobs:
      - lint-and-test:
          filters:
            tags:
              only: /.*/
      - docs:
          filters:
            branches:
              only: develop
      - publish:
          requires:
            - lint-and-test
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
